instruction: The robot must move forward 2 meters, turn left 180 degrees, set the gripper angle to 0.4, navigate to point (0, 5), and set the end-effector position to (0.4, 5.1, 1).
detailed_info:  
LLM: gpt-4o
stage: /home/winter/robot/evaluaiton/scenario_2/button/real_scene_phy.usd
initial position: [0,0,0]
initial_orientation: [1.0,0.0, 0.0, 0.0]
filter_by_distance: True
code_lines: |
