instruction: Ask the user for an object, then move to the vicinity of that object.
detailed_info:
LLM: gpt-4o
stage: /home/winter/robot/evaluaiton/scenario/room/real_scene_phy.usd
initial position: [0,0,0]
initial_orientation: [1.0,0.0, 0.0, 0.0]
filter_by_distance: True
code_lines: |
