task1: "Goto point(2,5) to see if there is a cup"
program1: |
  ```
  send_nav_goal(2,5,180);
  list = get_operable_objs();
  if "cup" in list: ...
  # Donâ€™t put mathematical expressions after the goto instruction; just specify a concrete coordinate directly.
  ```
