task1: "Goto point(2,5) to see if there is a cup"
program1: |
  ```
  goto 2,5,180;
  list = get_operable_objs;
  if "cup" in list: ...
  # Donâ€™t put mathematical expressions after the goto instruction; just specify a concrete coordinate directly.
  ```
task2: "Goto (3,8) with yaw 90"
program2: |
  ```
  goto 2,5,90;
  # If goto 3 places you can just write it 3 seperate goto command
  # don't wrtie this loop format!!!
  for 0 to 2 {  
  if 0 == 0 {  

    }  
  } else if 0 == 1 {  

    }  
  } else if 0 == 2 {  

    }  
  }  
  } 
  this is illeagal!!
  ```
