task1: "Goto point(2,5) to see if there is a cup"
program1: |
  ```
  send_nav_goal(2,5,180);
  list = get_operable_objs();
  if "cup" in list: ...
  # Don’t put mathematical expressions after the goto instruction; just specify a concrete coordinate directly.
  ```

task2: "The robot visit three different locations to find the user"
program2: |
  ```
  send_nav_goal(5.0,2.0,0);
  list = get_operable_objs();
  if "user" in list :
    approach("user");


  send_nav_goal(-4.0,-3.0,0);
  list = get_operable_objs();
  if "user" in list :
    approach("user");
  

  send_nav_goal(2.0,-6.0,0);
  list = get_operable_objs();
  if "user" in list :
    approach("user");
  
  # remember to import the api again！！
  ```