task1: "Goto point(2,5) to see if there is a cup"
program1: |
  ```
  goto 2,5,180;
  list = get_operable_objs;
  if "cup" in list: ...
  # Donâ€™t put mathematical expressions after the goto instruction; just specify a concrete coordinate directly.
  ```
task2: "Goto ..."
program2: |
  ```
  goto 2,5,90;
  # If goto 3 places you can just write it 3 seperate goto command
  # don't wrtie this loop format!!!
  for 0 to 2 {  
  if 0 == 0 {  

    }  
  } else if 0 == 1 {  

    }  
  } else if 0 == 2 {  

    }  
  }  
  } 
  this is illeagal!!
  ```

task3: "The robot visit three different locations to find the user"
program2: |
  ```
  goto 5.0, 2.0, 0; 
  list = get_operable_objs;
  if "user" in list {
    approach "user";
  }
  goto -4.0, -3.0, 0;
  list = get_operable_objs;
  if "user" in list {
    approach "user";
  }
  goto 2.0, -6.0, 0; 
  list = get_operable_objs;
  if "user" in list {
    approach "user";
  }
  # if I told you GOTO endpoint (6.200,-0.950) is occupied, try other point instead!!
  # only need to move the end-effector close to the button to press it
  # when using goto and set_end, do not use the task coordinates directly, but select nearby safe positions to avoid collision
  ```